name: Build Docker Image

on:
  push:
    branches: [main]
  schedule:
    # Runs "every Monday" (see https://crontab.guru)
    - cron: '0 0 * * MON'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest lucky version
        run: |
          LUCKY_VERSION=$(v=$(curl -s https://api.github.com/repos/zhz8888/lucky/releases/latest | jq -r '.tag_name'); echo ${v#?})
          echo "Latest Lucky version: $LUCKY_VERSION"
          echo LUCKY_VERSION=$LUCKY_VERSION >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/riscv64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/lucky:${{ env.LUCKY_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/lucky:latest
          build-args:
            TARGET_ARCH = linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/riscv64